### PR TITLE
add React 17 to peerDep range

### PR DESCRIPTION
**Pull request by atomicpages**
Fixes npm 7 install errors (really warnings) 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: example@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"0.14 - 16" from react-signature-canvas@1.0.3
npm ERR! node_modules/react-signature-canvas
npm ERR!   react-signature-canvas@"*" from the root project
```

### CODE REVIEW

**Comment by luke9216** [comment]
@agilgur5 This is a simple change. Please approve it.

**Comment by Shahaed** [comment]
@agilgur5

**Comment by agilgur5** [comment]
## have to re-set-up Travis CI

Normally I could merge in something like this pretty quickly, but apparently [CI has been down](https://travis-ci.org/github/agilgur5/react-signature-canvas) for like 6+ months as Travis decommissioned their `.org` domain.

Will have to re-set-up that and make sure all tests pass before merging

## thanks for the detail in the PR!

> npm 7 install errors (really warnings)

Thanks for logging the error here and noting they are just warnings @atomicpages ! I haven't done much front-end dev in the past year (my day job tends to be SRE-focused past few years) so I haven't actually tried NPM 7 myself yet.

## maintainers are human too, and also volunteers

To the other commenters, friendly reminder that one-word comments are spammy and you can use reactions instead. Also if a person has set on their status "Taking a break from toxicity and abuse 😞", probably not appropriate to spam their handle repeatedly, especially when GitHub tells you their status when doing so. 😐

**Review by agilgur5 — CHANGES_REQUESTED** [review]
Unfortunately there are some issues with this PR.

Per https://github.com/agilgur5/react-signature-canvas/issues/58#issuecomment-726995365, the devDeps need updating as well so that the tests use React 17.

This is actually a good bit easier said than done because the Enzyme Adapter has to be updated. Per https://github.com/enzymejs/enzyme/issues/2429, no official adapter is available yet for React 17.
React 17 has been a [complicated](https://github.com/enzymejs/enzyme/pull/2430#issuecomment-716327508) change for Enzyme, and as it only has [1 active contributor](https://github.com/enzymejs/enzyme/issues/2429#issuecomment-998082843), such complex roadblocks have caused it to stall.

There is an [unofficial adapter](https://github.com/wojtekmaj/enzyme-adapter-react-17) with partial support for React 17 though. It is likely enough for the use-case within this repo, so I'll try to get in an upgrade with that.

That being said, the author of the unofficial adapter has stated that React 18 support [requires even more complicated changes](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl). They suggest using [RTL](https://github.com/testing-library/react-testing-library), but it actually doesn't support instance methods, which, per my [first testing issue](https://github.com/agilgur5/react-signature-canvas/issues/33#issue-473708832), is a blocker as `react-signature-canvas` actually has a ref-based API and so needs tests for it.

So while we may be able to get by unofficially with the unofficial React 17 adapter, there's not much of a path for testing React 18 as of now.

**Comment by agilgur5** [comment]
Per [this blog post](https://dev.to/arqex/testing-with-react-testing-library-using-component-instances-nl6), looks like [`react-dom-instance`](https://github.com/arqex/react-dom-instance) + RTL could be an alternative to Enzyme for React 18. Though that library also hasn't been updated in 2 years and is also tested with React 16 😕

**Comment by agilgur5** [comment]
Replaced by #69

**Pull request closed without merging**
