### PR TITLE
(refactor): Wrap upstream signature_pad

### LINKED ISSUE #17: [RFC] Use/wrap upstream signature_pad
When I originally forked `react-signature-pad`, I did not particularly diff the code with the original `signature_pad` and just made changes downstream as needed. Having looked more closely at `signature_pad` in recent months (due to the discussion in #8 ), it looks like all of the code is backward-compatible (even the 2.0.0 release is just a dist change which does not break the API).

I propose that this library import `signature_pad` and effectively just act as a wrapper implementing certain helper functions like trimming and resizing (as it currently does). All props would be passed directly to the `signature_pad` instance. In order to preserve auto-updating props, a `componentWillReceiveProps` hook would need to be made that updates the instance's internal variables. I don't think there would be anything backwards-incompatible this way, but I may be wrong (there may be some gimmicks in resize). It may need to pin to patch versions only for now as minor version changes could break the wrapping layer due to internal usage (e.g. `opts.ratio`, `opts.width`, `opts.height`).

This would add a whole host of new functionality, such as adding an SVG option as requested in #12 , as well as fix lots of bugs, such as the `isEmpty` bug in #16 , and would overall reduce maintenance burden and the general surface area of this library and its API.

### PR DESCRIPTION
**Pull request by agilgur5**
Fixes #17

### CODE REVIEW

**Comment by agilgur5** [comment]
@lopis @kgram if you guys get a moment, could you review this? This resolves the RFC. I'll release the alpha version if all looks good so folks can test

**Comment by lopis** [comment]
Oh man, great cleanup job. :+1:

**Comment by lopis** [comment]
Maybe I'm doing something terribly wrong but I couldn't run the example without adding the `react` preset in a `.babelrc` file. Otherwise I kept getting `Module build failed: Error: Couldn't find preset "react" relative to directory "/home/joao/code"`

**Comment by agilgur5** [comment]
@lopis tbh, I hadn't ran the example in almost 2 years (since I made the fork haha), but ran `npm start` in my local copy and it worked no problem o.o. The `react` preset is specified in `webpack.config.js` so that a `.babelrc` isn't necessary.

Not sure if there might be a dependency conflict with your install (since the webpack and babel versions used here are out-of-date nowadays)

**Comment by lopis** [comment]
If it works on your side it must be some dependency on my side. If I find
something I'll let you know.

**Comment by agilgur5** [comment]
If this looks good, I'll release the alpha version tonight/tomorrow

**Comment by agilgur5** [comment]
Rebased in as https://github.com/agilgur5/react-signature-canvas/commit/a703e223fe09e99789ceac3e2bcdf96658bd92c8 and https://github.com/agilgur5/react-signature-canvas/commit/62c371419e5b39be60e1ecde71acc185292f1d58 and released as [v1.0.0-alpha.1](https://github.com/agilgur5/react-signature-canvas/releases/tag/v1.0.0-alpha.1). Thanks for the review @lopis !

If anyone can sees this can test the alpha within their own codebase, would be helpful and appreciated!

**Pull request closed without merging**
